apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: mongodb
    {{- include "contacts.labels" . | nindent 4 }}
type: Opaque
data:
  contacts_mongo_url: {{ .Values.contacts_mongo_url | b64enc }}
